version: "3.9"
services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    build: 
      context: .
      dockerfile: dev.Dockerfile
    # command: >
    # "npm run cli db seed -- --swe && pnpm dev"
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && pnpm dev"]
    volumes:
      - .:/etc/logto
      - /etc/logto/node_modules
    # entrypoint: ["sh", "-c", "pnpm dev"]
    ports:
      - 3001:3001
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgres://postgres:p0stgr3s@postgres/postgres
  postgres:
    image: postgres:14-alpine
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr3s
    ports:
      - 5433:5432  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5